### ISSUE TITLE
Not all sequences being classified

### ISSUE THREAD

**Issue by TimothyStephens** [LottePronk/whokaryote#1]
Hi,

I have noticed that not all of the sequences in `contigs5000.fasta` end up being classified. 
In my case, I end up with 4914 sequences in the `contigs5000.fasta`, 1009 in `eukaryotic_contigs.fasta` and 3890 in `prokaryotic_contigs.fasta`.
So there are 15 sequences that aren't being classified. 
Is this an expected behaviour?

Thanks for your help.
Tim.

**Comment by LottePronk** [comment]
Hi Tim,

Thank you for using Whokaryote! 

When prodigal detects less than 2 genes on a contig, important features such as intergenic distance cannot be calculated. Therefore, these contigs cannot be classified by Whokaryote. So, likely, these 15 sequences you are missing have less than 2 genes on them. If you have the time to check this that would be great, so we can rule out any other cause. 

I will try to add a warning message to the output whenever contigs < 2 genes are detected, so that it is clear to anyone who uses the tool why some contigs are missing.

Please let me know if you have any more questions!

Lotte

**Comment by TimothyStephens** [comment]
Hi Lotte,

Thanks for the quick response. 
You are right, those contigs have < 2 predicted genes.

Thanks for your help.
Tim.
