### ISSUE TITLE
Is it reasonable to use prodigal to predict eukaryotes genes?

### ISSUE THREAD

**Issue by yan1365** [LottePronk/whokaryote#10]
Hi,

I noticed Whokaryote use prodigal to identify "genes" in the contigs (which could be either prokaryotes or eukaryotes). And the prodigal results are major inputs for the random forest classifier. However, it is clearly stated in prodigal paper that, it was only designed for predicting prokaryotes genes. Therefore, I am wondering how valid it is to use prodigal to calculate gene density and other related features?

Thanks,
Ming

**Comment by tiantianlili** [comment]
@yan1365 Hello, I have the same confusion with you, I wonder if you have a solution now? I have noticed that the prediction tools of eukaryotic functional genes based on contigs are limited, and it may be appropriate to make the prediction of functional genes after obtaining eukaryotic MAGs？

**Comment by yan1365** [comment]
> @yan1365 Hello, I have the same confusion with you, I wonder if you have a solution now? I have noticed that the prediction tools of eukaryotic functional genes based on contigs are limited, and it may be appropriate to make the prediction of functional genes after obtaining eukaryotic MAGs？

Hi, you may want to check https://doi.org/10.1186/s40168-020-00808-x

**Comment by tiantianlili** [comment]
@yan1365 Thank you very much, this will be very helpful to me! If it is convenient for you, could you share CNS-level research article, including identification of eukaryotic from meta genome data, eukaryotic taxonomy, functional genes prediction and annotation (based on contig and MAG) (I have known how to analysis based on contigs but not MAGs). I'm frustrated that I could not find high-level reference that include full process analysis.

**Comment by LottePronk** [comment]
Hi @yan1365 , I am fully aware that prodigal is designed for prokaryotic gene prediction! In short, I use prodigal because it's fast and works well enough to be able to train a random forest classifier that can make accurate predictions. In most metagenomes, the majority of contigs are prokaryotic, and the prodigal prediction is the most accurate. Whokaryote then predicts which contigs are probably eukaryotic. I highly suggest to use a eukaryotic gene predictor on the contigs that were predicted to be eukaryotic, for more accurate gene prediction. In fact, it's the whole reason I developed Whokaryote, to know which contigs are eukaryotic, so I can predict genes more accurately on those contigs with eukaryote-specific gene predictors. Most eukaryotic gene predictors require a huge database or pre-trained, organism-specific models, and it doesn't make sense to run this on an entire metagenome when maybe only a small portion is eukaryotic. And most people run prodigal (or another prokaryotic gene predictor) anyway on a metagenome, so they may have the files already, which can be given as input to Whokaryote. To me, it makes sense to first predict if a contig is eukaryotic before doing gene prediction, and that is what Whokaryote does. It just happens to use features derived from suboptimal gene predictions. Despite that, it still works, because the suboptimal gene predictions carry specific signatures as well (by being suboptimal, and therefore a bit weird sometimes) that are likely picked up by the model. The prodigal predictions aren't meant to be accurate for eukaryotes, we've got eukaryotic gene predictors for that once we know a contig is eukaryotic. I've discussed most of what I said here in the paper as well. @tiantianlili  I'm currently working on a metagenome analysis pipeline that makes use of Whokaryote, and includes eukaryote-specific downstream tools and does the things that you're talking about.
